modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "ezunclear"
version = "${version}"
displayName = "EzUnclear"
authors = "Kall"
description = '''
A Minecraft mod
'''
#logoFile = ""

[[mixins]]
config = "ezunclear.mixins.json"
